### PR TITLE
check for java 11

### PR DESCRIPTION
**Pull request by jimscarver**

### CODE REVIEW

**Comment by dckc** [comment]
Why check for Java 11? What are the symptoms if you use a different version of java?

**Comment by jimscarver** [comment]
I don't remember. It has been a long time since I had to install java 11 I don't remember how it failed. The instructions were to install java 11 which is not necessary if you already have java 11.

**Comment by dckc** [comment]
ah. I see.

I wonder if it's really worth the screenspace. I expect a lot of people who have java 11 installed are aware that they don't need to install it.

**Comment by jimscarver** [comment]
Sure I guess you can remove the whole install java section. I have not had to do that is some time. It is listed as a prereq for Other Linux distributions... If I remember correctly the requirement for 11 may even have been dropped because so many had problems installing it back in 2018

**Pull request closed without merging**
